<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
  </PropertyGroup>

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <Version>0.1.0-preview1</Version>
    <Authors>Paweł Łukasik</Authors>
    <Company>Paweł Łukasik</Company>
    <Copyright>Copyright (c) 2026 Paweł Łukasik</Copyright>
    <PackageProjectUrl>https://github.com/pawlos/covenant</PackageProjectUrl>
    <RepositoryUrl>https://github.com/pawlos/covenant</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageReadmeFile>NUGET-README.md</PackageReadmeFile>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>
</Project>
