<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" Version="0.13.12" />
    <ProjectReference Include="..\..\src\Showcase.Http.Naive\Showcase.Http.Naive.csproj" />
    <ProjectReference Include="..\..\src\Showcase.Http.Optimized\Showcase.Http.Optimized.csproj" />
  </ItemGroup>
</Project>
